"""Aggregation point for all SQLAlchemy models in the application.

Alembic's env.py imports this package with `from app.models import *` so that
every model class gets registered on Base.metadata before migrations are
autogenerated or run - without this, a model defined but not imported here
would be invisible to Alembic. As new modules (expenses, retirement,
investments, planning) are added in later phases, their models should be
exported here too.
"""

from app.models.user import User
from app.models.bank_accounts import BankAccount, RecurringAction, BankTransaction
from app.models.retirement_accounts import RetirementAccount, RetirementRecurringContribution
from app.models.education_accounts import EducationAccount, EducationRecurringContribution
from app.models.receipts import Receipt, ReceiptLineItem
from app.models.expense_categories import ExpenseCategory
from app.models.expenses import Expense
from app.models.income import Income, IncomeAllocation
from app.models.transactions import Transaction
from app.models.investments import StockPosition, StockTransaction, BondHolding, PropertyInvestment

__all__ = [
    "User",
    "BankAccount",
    "RecurringAction",
    "BankTransaction",
    "RetirementAccount",
    "RetirementRecurringContribution",
    "EducationAccount",
    "EducationRecurringContribution",
    "Receipt",
    "ReceiptLineItem",
    "ExpenseCategory",
    "Expense",
    "Income",
    "IncomeAllocation",
    "Transaction",
    "StockPosition",
    "StockTransaction",
    "BondHolding",
    "PropertyInvestment",
]
